#FROM node:24.15.0-bookworm
FROM registry.redhat.io/ubi10/nodejs-24:latest

ENV OPENCODE_VERSION=1.17.7

# set working directory
WORKDIR ${APP_ROOT}

RUN OPENCODE_INSTALL_DIR=${APP_ROOT} \
    curl -fsSL https://opencode.ai/install | bash -s -- --version ${OPENCODE_VERSION}

ENV PATH=${APP_ROOT}/src/.opencode/bin:$PATH \
    OPENCODE_DB=${APP_ROOT}/data/opencode.db \
    XDG_DATA_HOME=${APP_ROOT}/data \
    XDG_CONFIG_HOME=${APP_ROOT}/config \
    XDG_STATE_HOME=${APP_ROOT}/state \
    XDG_CACHE_HOME=${APP_ROOT}/cache

RUN opencode --help

RUN mkdir -p ${APP_ROOT}/data && \
    mkdir -p ${APP_ROOT}/config && \
    mkdir -p ${APP_ROOT}/state && \
    mkdir -p ${APP_ROOT}/cache && \
    chown -R 1001:0 ${APP_ROOT} && chmod -R ug+rwx ${APP_ROOT}

# set the user to 1001
USER 1001

# create necessary directories and set permissions
#RUN mkdir -p /home/opencode/.local/share/opencode/ && \
#  mkdir -p /home/opencode/.local/state/opencode && \
#  mkdir -p /home/opencode/.config/opencode/ && \
#  chown -R opencode:opencode /home/opencode

