#!/bin/bash
set -e

if [ -n "${GIT_REPO}" ]; then
    if [ ! -d "/projects/.git" ]; then
        git clone "${GIT_REPO}" "/projects"
    fi

    if [ -n "${GIT_REV}" ]; then
        git -C "/projects" checkout "${GIT_REV}"
    elif [ -n "${GIT_BRANCH}" ]; then
        git -C "/projects" checkout "${GIT_BRANCH}"
    fi
elif [ ! -d "/projects/.git" ]; then
    git init "/projects"
fi

cd "/projects"
opencode ${OPENCODE_MODE} --hostname ${OPENCODE_HOSTNAME} --port ${OPENCODE_PORT}
